managers/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'managers'

urlpatterns = [
    path('my_profile/', views.manager_area, name='manager_area'),
    path('view_report/<str:report_filename>/', views.view_report, name='view_report'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

starlingua/urls.py
from django.contrib import admin
from django.urls import path, include
from students.management.commands.telegram_bot import telegram_webhook
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('teachers/', include('teachers.urls')),
    path('students/', include('students.urls')),
    path('turnover/', include('turnover.urls')),
    path('schedule/', include('schedule.urls')),
    path('manager/', include('managers.urls')),
    path('webhook/', telegram_webhook, name='telegram_webhook'),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

turnover/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'turnover'

urlpatterns = [
    path('manage/', views.manage_turnover, name='manage_turnover'),
    path('manage/edit/<int:pk>/', views.edit_turnover, name='edit_turnover'),
    path('manage/add/', views.add_turnover, name='add_turnover'),
    path('manage/school/', views.manage_school, name='manage_school'),
    path('manage/school/edit/<int:pk>/', views.edit_school, name='edit_school'),
    path('manage/school/add/', views.add_school, name='add_school'),
    path('manage/salary/', views.manage_salary, name='manage_salary'),
    path('manage/salary/edit/<int:pk>/', views.edit_salary, name='edit_salary'),
    path('manage/salary/add/', views.add_salary, name='add_salary'),
    path('manage/client/', views.manage_client, name='manage_client'),
    path('manage/client/edit/<int:pk>/', views.edit_client, name='edit_client'),
    path('manage/client/add/', views.add_client, name='add_client'),
    path('manage/teacher_calculation/', views.manage_teacher_calculation, name='manage_teacher_calculation'),
    path('manage/teacher_calculation/edit/<int:pk>/', views.edit_teacher_calculation, name='edit_teacher_calculation'),
    path('manage/teacher_calculation/add/', views.add_teacher_calculation, name='add_teacher_calculation'),
    path('manage/total_turnover/', views.manage_total_turnover, name='manage_total_turnover'),
    path('manage/total_turnover/edit/<int:pk>/', views.edit_total_turnover, name='edit_total_turnover'),
    path('manage/turnover/delete/<int:pk>/', views.delete_turnover, name='delete_turnover'),
    path('manage/teacher_calculation/delete/<int:pk>/', views.delete_teacher_calculation,
         name='delete_teacher_calculation'),
    path('manage/school/delete/<int:pk>/', views.delete_school, name='delete_school'),
    path('manage/client/delete/<int:pk>/', views.delete_client, name='delete_client'),
    path('manage/salary/delete/<int:pk>/', views.delete_salary, name='delete_salary'),
    path('teachers/', views.teacher_list, name='teacher_list'),
    path('students/', views.student_list, name='student_list'),
    path('assign_student/<int:teacher_id>/', views.assign_student, name='assign_student'),
    path('add_teacher/', views.add_teacher, name='add_teacher'),
    path('add_student/', views.add_student, name='add_student'),
    path('delete_teacher/<int:teacher_id>/', views.delete_teacher, name='delete_teacher'),
    path('delete_student/<int:student_id>/', views.delete_student, name='delete_student'),
    path('assign_student/<int:teacher_id>/', views.assign_student, name='assign_student'),
    path('unassign_student/<int:teacher_id>/<int:student_id>/', views.unassign_student, name='unassign_student'),
    path('schedule/', views.manage_schedule, name='manage_schedule'),
    path('add_lesson', views.add_lesson, name='add_lesson'),
    path('edit_lesson/<int:lesson_id>/', views.edit_lesson, name='edit_lesson'),
    path('delete_lesson/<int:lesson_id>/', views.delete_lesson, name='delete_lesson'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'users'

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

managers/models.py
from django.contrib.auth.models import User
from django.db import models


class Manager(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    surname = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=20)
    salary = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def __str__(self):
        return self.name

managers/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
import os
from django.http import HttpResponse, JsonResponse, Http404
from django.core.management import call_command
from django.utils import timezone
from django.conf import settings
import mimetypes
from django.shortcuts import get_object_or_404
from teachers.models import Teacher


@login_required
def manager_area(request):
    teachers = Teacher.objects.all()
    if request.method == "POST" and request.POST.get("update_period"):
        call_command("update_period")
        return JsonResponse({"message": "Успешно обновлено"}, status=200)

    export_path = os.path.join(settings.MEDIA_ROOT, 'turnover_exports')
    report_files = []
    if os.path.exists(export_path):
        report_files = [f for f in os.listdir(export_path) if f.endswith('.xlsx')]

    context = {
        'report_files': report_files,
        "teachers": teachers,
    }
    return render(request, 'managers/manager_area.html', context)


def view_report(request, report_filename):
    report_path = os.path.join(settings.MEDIA_ROOT, 'turnover_exports', report_filename)

    if not os.path.exists(report_path):
        raise Http404("Report not found.")

    mime_type, _ = mimetypes.guess_type(report_path)
    if not mime_type:
        raise Http404("Unsupported file type.")

    with open(report_path, 'rb') as f:
        response = HttpResponse(f.read(), content_type=mime_type)

    if request.GET.get('download') == 'true':
        response['Content-Disposition'] = f'attachment; filename="{report_filename}"'
    else:
        response['Content-Disposition'] = f'inline; filename="{report_filename}"'

    return response

managers/templates/managers/manager_area.html
{% extends "users/base.html" %}

{% block content %}
<header>
    <h1>Добро пожаловать, {{ manager.name }}!</h1>
</header>
<nav>
    <ul>
        <li><a href="{% url 'turnover:manage_turnover' %}">Бухгалтерия</a></li>
    </ul>
</nav>
<main>
    <section id="update-turnover">
        <button id="update-period-button">Обновить период учета</button>
        <p id="update-message"></p>
    </section>

    <section id="excel-files">
        <h2>Архив отчетов:</h2>
        {% if report_files %}
            <ul>
                {% for report in report_files %}
                    <li>
                        <a href="{% url 'managers:view_report' report %}?download=true" target="_blank">Завантажити {{ report }}</a> |
                        <a href="{% url 'managers:view_report' report %}" target="_blank">Дивитись {{ report }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Файлы не найдены.</p>
        {% endif %}
    </section>
    <section id="teachers-salaries">
        <h2>Зарплаты преподавателей:</h2>
        {% if teachers %}
            <ul>
                {% for teacher in teachers %}
                    <li>{{ teacher.name }} {{ teacher.surname }} - {{ teacher.salary }} грн.</li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Преподаватели не найдены.</p>
        {% endif %}
    </section>
</main>

<script>
document.getElementById("update-period-button").addEventListener("click", function() {
    fetch("{% url 'managers:manager_area' %}", {
        method: "POST",
        headers: {
            "X-CSRFToken": "{{ csrf_token }}",
        },
        body: new URLSearchParams({
            "update_period": "1"
        })
    })
    .then(response => response.json())
    .then(data => {
        document.getElementById("update-message").textContent = data.message;
    })
    .catch(error => {
        console.error("Ошибка:", error);
        document.getElementById("update-message").textContent = "Ошибка обновления.";
    });
});
</script>
{% endblock %}