schedule/urls.py
from django.urls import path
from . import views

app_name = 'schedule'

urlpatterns = [
    path('schedule/', views.schedule_view, name='schedule_view'),
    path('mark-lesson-conducted/<int:lesson_id>/', views.mark_lesson_conducted, name='mark_lesson_conducted'),
    path('add-lesson/', views.add_lesson, name='add_lesson'),
    path('edit-lesson/<int:lesson_id>/', views.edit_lesson, name='edit_lesson'),
    path('delete-lesson/<int:lesson_id>/', views.delete_lesson, name='delete_lesson'),
]

starlingua/urls.py
from django.contrib import admin
from django.urls import path, include
from students.management.commands.telegram_bot import telegram_webhook
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('teachers/', include('teachers.urls')),
    path('students/', include('students.urls')),
    path('turnover/', include('turnover.urls')),
    path('schedule/', include('schedule.urls')),
    path('manager/', include('managers.urls')),
    path('webhook/', telegram_webhook, name='telegram_webhook'),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teachers/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings


app_name = 'teachers'

urlpatterns = [
    path('profile/', views.teacher_profile, name='teacher_profile'),
    path('profile/done/', views.teacher_profile_done, name='teacher_profile_done'),
    path('my_profile', views.teacher_area, name='teacher_area'),
    path('upload-material/', views.upload_material, name='upload_material'),
    path('view-material/<int:material_id>/', views.view_material, name='view_material'),
    path('delete-material/<int:material_id>/', views.delete_material, name='delete_material'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'users'

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teachers/models.py
from django.db import models
from students.models import Student
from django.conf import settings

class Teacher(models.Model):
    name = models.CharField(max_length=255)
    surname = models.CharField(max_length=255)
    student = models.ManyToManyField(Student, related_name='teachers')
    phone_number = models.CharField(max_length=20)
    student_phone_number = models.CharField(max_length=20, null=True, blank=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    salary = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    conducted_lessons = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Material(models.Model):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='materials')
    name = models.CharField(max_length=255)
    file = models.FileField(upload_to='materials/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

teachers/forms.py
from django import forms
from .models import Teacher, Material


class TeacherProfileForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ['name', 'surname', 'phone_number']
        labels = {
            'name': 'Імʼя',
            'surname': 'Прізвище',
            'phone_number': 'Номер телефону',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'surname': forms.TextInput(attrs={'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
        }


class MaterialUploadForm(forms.ModelForm):
    class Meta:
        model = Material
        fields = ['file']

teachers/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import TeacherProfileForm, MaterialUploadForm
from django.contrib.auth.decorators import login_required
from .models import Material
from schedule.models import Lesson
from django.utils import timezone
from django.http import HttpResponse, Http404
import mimetypes


def teacher_profile(request):
    if request.method == 'POST':
        form = TeacherProfileForm(request.POST)
        if form.is_valid():
            teacher_profile = form.save(commit=False)
            teacher_profile.user = request.user
            teacher_profile.salary = 0
            teacher_profile.save()
            return redirect('teachers:teacher_profile_done')
    else:
        form = TeacherProfileForm()

    return render(request, 'teachers/teacher_profile.html', {'form': form})


def teacher_profile_done(request):
    return render(request, 'teachers/teacher_profile_done.html')


@login_required
def teacher_area(request):
    teacher = request.user.teacher
    materials = teacher.materials.all()
    students = teacher.student.all()
    current_salary = teacher.salary

    lessons = Lesson.objects.filter(teacher=teacher)

    events = []
    for lesson in lessons:
        event = {
            'title': f'{lesson.student.name}',
            'start': lesson.date.isoformat() + 'T' + lesson.start_time.strftime('%H:%M:%S'),
        }
        if lesson.conducted:
            event['classNames'] = ['conducted-lesson']
        events.append(event)

    context = {
        'teacher': teacher,
        'materials': materials,
        'students': students,
        'current_salary': current_salary,
        'events': events,
    }
    return render(request, 'teachers/teacher_area.html', context)


@login_required
def upload_material(request):
    if request.method == 'POST':
        form = MaterialUploadForm(request.POST, request.FILES)
        if form.is_valid():
            material = form.save(commit=False)
            material.teacher = request.user.teacher
            material.name = request.FILES['file'].name
            material.save()
            return redirect('teachers:teacher_area')
    else:
        form = MaterialUploadForm()
    return render(request, 'teachers/upload_material.html', {'form': form})


@login_required
def delete_material(request, material_id):
    material = get_object_or_404(Material, id=material_id, teacher=request.user.teacher)
    material.delete()
    return redirect('teachers:teacher_area')


@login_required
def view_material(request, material_id):
    material = get_object_or_404(Material, id=material_id)
    mime_type, _ = mimetypes.guess_type(material.file.path)

    if not mime_type:
        raise Http404("Unsupported file type.")

    response = HttpResponse(material.file.read(), content_type=mime_type)

    if request.GET.get('download') == 'true':
        response['Content-Disposition'] = f'attachment; filename="{material.file.name}"'
    else:
        response['Content-Disposition'] = f'inline; filename="{material.file.name}"'

    return response

teachers/templates/teachers/teacher_area.html
{% extends "users/base.html" %}

{% block content %}
<header>
    <h1>Вітаємо, {{ user.teacher.name }}!</h1>
</header>
<nav>
    <ul>
        <li><a href="{% url 'schedule:add_lesson' %}">Добавить урок</a></li>
        <li><a href="{% url 'schedule:schedule_view' %}">Расписание</a></li>
    </ul>
</nav>
<main>
    <section id="manage-students">
        <h2>Учні</h2>
        <ul>
            {% for student in user.teacher.student.all %}
                <li>{{ student.name }} {{ student.surname }}</li>
            {% endfor %}
        </ul>
    </section>
    <section id="resources">
        <h2>Навчальний матеріал</h2>
        <form action="{% url 'teachers:upload_material' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="file">
            <button type="submit">Завантажити файл</button>
        </form>
        <ul>
            {% for material in user.teacher.materials.all %}
                <li>
                    <a href="{% url 'teachers:view_material' material.id %}?download=true" target="_blank">Завантажити {{ material.name }}</a> |
                    <a href="{% url 'teachers:view_material' material.id %}" target="_blank">Дивитись {{ material.name }}</a> |
                    <a href="{% url 'teachers:delete_material' material.id %}" class="delete-link">Видалити</a>
                </li>
            {% endfor %}
        </ul>
    </section>
    <section id="salary-info">
        <h2>Заробітня плата</h2>
        <p>Заробітня плата за поточний період: {{ teacher.salary }} грн.</p>
    </section>
    <h2>Календар</h2>
    <section id="calendar">
        <div id='calendar'></div>
    </section>
</main>

<link href='https://cdn.jsdelivr.net/npm/fullcalendar@5.11.3/main.min.css' rel='stylesheet' />
<script src='https://cdn.jsdelivr.net/npm/fullcalendar@5.11.3/main.min.js'></script>

<style>
    #calendar {
        max-width: 1500px;
        margin: 0 auto;
        height: 800px;
    }


    .fc .fc-daygrid-day-top {
        font-size: 14px;
    }



    .fc .fc-daygrid-event {
        font-size: 12px;
        color: #000000;
    }

    .conducted-lesson {
        background-color: #228b22;
        text-decoration: line-through; /* зачёркивание текста */
    }
</style>

<script>
document.addEventListener('DOMContentLoaded', function() {
    var calendarEl = document.getElementById('calendar');
    var calendar = new FullCalendar.Calendar(calendarEl, {
        initialView: 'dayGridMonth',
        locale: 'uk',
        events: {{ events|safe }},
        height: 'auto',
        contentHeight: 800,
        eventClassNames: function(arg) {
            return arg.event.extendedProps.classNames || '';
        }
    });
    calendar.render();
});
</script>
{% endblock %}

teachers/templates/teachers/teacher_profile.html
{% extends "users/base.html" %}

{% block content %}
<h2>Заповнення профілю викладача</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Зберегти</button>
</form>
{% endblock %}

teachers/templates/teachers/teacher_profile_done.html
{% extends "users/base.html" %}

{% block content %}
<h2>Профіль викладача успішно заповнений!</h2>
{% endblock %}

teachers/templates/teachers/upload_material.html
{% extends "users/base.html" %}

{% block content %}
<h2>Завантаження матеріалу</h2>
<form action="{% url 'teachers:upload_material' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Завантажити файл</button>
</form>
{% endblock %}