starlingua/urls.py
from django.contrib import admin
from django.urls import path, include
from students.management.commands.telegram_bot import telegram_webhook
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('teachers/', include('teachers.urls')),
    path('students/', include('students.urls')),
    path('turnover/', include('turnover.urls')),
    path('schedule/', include('schedule.urls')),
    path('manager/', include('managers.urls')),
    path('webhook/', telegram_webhook, name='telegram_webhook'),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

turnover/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'turnover'

urlpatterns = [
    path('manage/', views.manage_turnover, name='manage_turnover'),
    path('manage/edit/<int:pk>/', views.edit_turnover, name='edit_turnover'),
    path('manage/add/', views.add_turnover, name='add_turnover'),
    path('manage/school/', views.manage_school, name='manage_school'),
    path('manage/school/edit/<int:pk>/', views.edit_school, name='edit_school'),
    path('manage/school/add/', views.add_school, name='add_school'),
    path('manage/salary/', views.manage_salary, name='manage_salary'),
    path('manage/salary/edit/<int:pk>/', views.edit_salary, name='edit_salary'),
    path('manage/salary/add/', views.add_salary, name='add_salary'),
    path('manage/client/', views.manage_client, name='manage_client'),
    path('manage/client/edit/<int:pk>/', views.edit_client, name='edit_client'),
    path('manage/client/add/', views.add_client, name='add_client'),
    path('manage/teacher_calculation/', views.manage_teacher_calculation, name='manage_teacher_calculation'),
    path('manage/teacher_calculation/edit/<int:pk>/', views.edit_teacher_calculation, name='edit_teacher_calculation'),
    path('manage/teacher_calculation/add/', views.add_teacher_calculation, name='add_teacher_calculation'),
    path('manage/total_turnover/', views.manage_total_turnover, name='manage_total_turnover'),
    path('manage/total_turnover/edit/<int:pk>/', views.edit_total_turnover, name='edit_total_turnover'),
    path('manage/turnover/delete/<int:pk>/', views.delete_turnover, name='delete_turnover'),
    path('manage/teacher_calculation/delete/<int:pk>/', views.delete_teacher_calculation,
         name='delete_teacher_calculation'),
    path('manage/school/delete/<int:pk>/', views.delete_school, name='delete_school'),
    path('manage/client/delete/<int:pk>/', views.delete_client, name='delete_client'),
    path('manage/salary/delete/<int:pk>/', views.delete_salary, name='delete_salary'),
    path('teachers/', views.teacher_list, name='teacher_list'),
    path('students/', views.student_list, name='student_list'),
    path('assign_student/<int:teacher_id>/', views.assign_student, name='assign_student'),
    path('add_teacher/', views.add_teacher, name='add_teacher'),
    path('add_student/', views.add_student, name='add_student'),
    path('delete_teacher/<int:teacher_id>/', views.delete_teacher, name='delete_teacher'),
    path('delete_student/<int:student_id>/', views.delete_student, name='delete_student'),
    path('assign_student/<int:teacher_id>/', views.assign_student, name='assign_student'),
    path('unassign_student/<int:teacher_id>/<int:student_id>/', views.unassign_student, name='unassign_student'),
    path('schedule/', views.manage_schedule, name='manage_schedule'),
    path('add_lesson', views.add_lesson, name='add_lesson'),
    path('edit_lesson/<int:lesson_id>/', views.edit_lesson, name='edit_lesson'),
    path('delete_lesson/<int:lesson_id>/', views.delete_lesson, name='delete_lesson'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'users'

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(max_length=10, choices=[('student', 'Ученик'), ('teacher', 'Учитель')])

    def __str__(self):
        return self.user.username

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import UserProfile

class RegisterForm(UserCreationForm):
    ROLE_CHOICES = (
        ('student', 'Учень'),
        ('teacher', 'Викладач'),
    )

    username = forms.CharField(max_length=100, required=True, widget=forms.TextInput())
    email = forms.CharField(max_length=254, required=True, widget=forms.EmailInput())
    password1 = forms.CharField(max_length=50, required=True, widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50, required=True, widget=forms.PasswordInput())
    role = forms.ChoiceField(choices=ROLE_CHOICES, required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'role']

    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.save()
            UserProfile.objects.create(user=user, role=self.cleaned_data['role'])
        return user


class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from .forms import RegisterForm, LoginForm


def main(request):
    return render(request, 'users/index.html')


def home(request):
    return render(request, 'users/test.html')


def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='users:home')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            if user is not None:
                login(request, user)
                if form.cleaned_data['role'] == 'student':
                    return redirect('students:student_profile')
                elif form.cleaned_data['role'] == 'teacher':
                    return redirect('teachers:teacher_profile')
        else:
            return render(request, 'users/signup.html', {'form': form})

    form = RegisterForm()
    return render(request, 'users/signup.html', {'form': form})


def loginuser(request):
    if request.user.is_authenticated:
        return redirect(to='users:home')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])

        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='users:home')

    return render(request, 'users/login.html', context={"form": LoginForm()})


@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='users:home')


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your\
                        password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>STARLINGUA</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'users/style.css' %}">
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        <ul>
            <li><a href="/" role="button"> Go back to the main page</a></li>
            {% if 'turnover' in request.path %}
                <li><a href="{% url 'turnover:manage_turnover' %}" role="button">Оборот-Дохід-Витрати</a></li>
                <li><a href="{% url 'turnover:manage_school' %}" role="button">Школа</a></li>
                <li><a href="{% url 'turnover:manage_salary' %}" role="button">заробітня плата</a></li>
                <li><a href="{% url 'turnover:manage_client' %}" role="button">Клієнти</a></li>
                <li><a href="{% url 'turnover:manage_teacher_calculation' %}" role="button">Розрахунок викладачів</a></li>
                <li><a href="{% url 'turnover:manage_total_turnover' %}" role="button">Загальний ОДВ</a></li>
                <li><a href="{% url 'turnover:student_list' %}" role="button">Список учнів</a></li>
                <li><a href="{% url 'turnover:teacher_list' %}" role="button">Список викладачів</a></li>
                <li><a href="{% url 'turnover:manage_schedule' %}" role="button">Розклад</a></li>

            {% endif %}
        </ul>
    </nav>

    {% block content %} {% endblock %}
</main>
</body>
</html>

users/templates/users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Personal assistant</title>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'contacts/images/favicon.ico' %}"/>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    <!-- <link rel="stylesheet" href="{% static 'contacts/bootstrap.min.css' %}"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'contacts/main.css' %}">
    <link rel="stylesheet" href="{% static 'contacts/style.css' %}">
</head>
<body>

    <div class="container">
        <div class="row header-box">
            <div class="col-md-2 logo">
                <a href="/"><img src="{% static 'contacts/images/logo.JPG'%}" alt="Organize Pro"></a>
            </div>
            <div class="col-md-10">

                <div class="per-assist-menu-container">
                    {% if user.is_authenticated %}
                    <div class="per-assist-menu">
                        <div class="user-menu">
                            <ul>
                            </ul>
                        </div>
                        <div class="user-login-menu">
                            <ul>
                                <li>Welcome <b>{{ user.username }}!</b></li>
                                <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
                            </ul>
                        </div>
                    </div>
                    {% else %}
                    <div class="per-assist-menu">
                        <div class="user-login-menu">
                            <ul>
                                <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
                                <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
                            </ul>
                        </div>
                    </div>
                    {% endif %}  
                </div>     

            </div>
        </div>          

        <div class="row">
            
            <div class="col-md-3 left-column">

                {% if request_path == "/turnover/manage/" %}
                    <div class="nav flex-column nav-pills">
                        <a class="nav-link" href="{% url 'turnover:manage_turnover' %}">Управление оборотом</a>
                        <a class="nav-link" href="{% url 'turnover:manage_school' %}">Управление школами</a>
                        <a class="nav-link" href="{% url 'turnover:manage_salary' %}">Управление зарплатами</a>
                        <a class="nav-link" href="{% url 'turnover:manage_client' %}">Управление клиентами</a>
                        <a class="nav-link" href="{% url 'turnover:manage_teacher_calculation' %}">Управление расчетами преподавателей</a>
                        <a class="nav-link" href="{% url 'turnover:manage_total_turnover' %}">Управление общим оборотом</a>
                    </div>
                {% endif %}

                {#% if user.is_authenticated %#}
                    {% if date != "" %}
                    <div class="exchange_rates_block block">
                        <div><h4>Exchange rates</h4></div>
                        <div class="date"><h5>{{date}}</h5></div>
                        <div class="rates">
                            {% for rate in rates %}
                                <div>{{rate.purchaseRate}} &nbsp; {{rate.currency}} &nbsp; {{rate.saleRate}}</div>
                            {% endfor %}
                        </div>
                    </div>
                    {% endif %}

                    <!-- <div>
                        <div>
                            <h4>Current weather for {{ weather.location }}</h4>
                            <p>Temperature: {{ weather.temperature }}°C</p>
                            <p>Description: {{ weather.description }}</p>
                            <p>Last update: {{ weather.timestamp }}</p>
                        </div>
                    </div> -->
                {#% endif %#}

            </div>

            <div class="col-md-9">
                
                {% block content %}
                
                    {% if user.is_authenticated %}
                        <div>
                            {% for contact in contact_list %}
                                <div class="contact-item">
                                    <div class="items"><a href="{% url 'contacts:contact_detail' contact.id %}">{{ contact.name }} {{ contact.surname }}</a></div>
                                    <div class="items">{{ contact.phone }}</div>
                                    <div class="items">{{ contact.email }}</div>
                                    <div class="contact-buttons">
                                        <button type="submit" onclick="window.location.href = '{% url 'contacts:edit_contact' contact.id %}';">Edit</button>
                                        <form method="post" action="{% url 'contacts:delete_contact' contact.id %}" style="display:inline;">
                                            {% csrf_token %}
                                            <button type="submit" onclick="return confirm('Are you sure you want to delete this contact?');">Delete</button>
                                        </form>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>

                        <div>
                            <nav>
                                <ul class="pager">
                                    
                                    <li class="previous">
                                        {% if contact_list.has_previous %}
                                        <a href="?page=1"><span aria-hidden="true">←←</span> First</a>
                                        <a href="?page={{ contact_list.previous_page_number }}"><span aria-hidden="true">←</span> Previous</a>
                                        {% endif %}                        
                                    </li>
                                    
                                    <span class="current">
                                        Page {{ contact_list.number }} of {{ contact_list.paginator.num_pages }}.
                                    </span>
                    
                                    <li class="next">
                                        {% if contact_list.has_next %}
                                        <a href="?page={{ contact_list.paginator.num_pages }}">Last <span aria-hidden="true">→→</span></a>
                                        <a href="?page={{ contact_list.next_page_number }}">Next <span aria-hidden="true">→</span></a>
                                        {% endif %}
                                    </li>
                                </ul>
                            </nav>         
                        </div>
                    {% endif %}   
                    
                    {% if not user.is_authenticated %}

                        {% for n in news_main_not_auth %}
                            <h2><a href="{% url 'the_news:news_detail' n.id %}">{{ n.title }}</a></h2>
                            <p>{{ n.content }}</p>
                            <p>Category: {{ n.category }}</p>
                            <p>Published: {{ n.published_date }}</p>
                        {% endfor %}

                        <div>
                            <nav>
                                <ul class="pager">
                                    
                                    <li class="previous">
                                        {% if news_main_not_auth.has_previous %}
                                        <a href="?page=1"><span aria-hidden="true">←←</span> First</a>
                                        <a href="?page={{ news_main_not_auth.previous_page_number }}"><span aria-hidden="true">←</span> Previous</a>
                                        {% endif %}                        
                                    </li>
                                    
                                    <span class="current">
                                        Page {{ news_main_not_auth.number }} of {{ news_main_not_auth.paginator.num_pages }}.
                                    </span>
                    
                                    <li class="next">
                                        {% if news_main_not_auth.has_next %}
                                        <a href="?page={{ news_main_not_auth.paginator.num_pages }}">Last <span aria-hidden="true">→→</span></a>
                                        <a href="?page={{ news_main_not_auth.next_page_number }}">Next <span aria-hidden="true">→</span></a>
                                        {% endif %}
                                    </li>
                                </ul>
                            </nav>         
                        </div>


                    {% endif %} 
                
                {% endblock %}

            </div>

        </div>
    </div>

    <footer class="footer">
        <div class="container">
            <p class="copyright">
                © 2024, made by <span class="copy">Pythonic wizards team</span>
            </p>
        </div>
    </footer>

    <div id="gadsf21g"></div><div at-magnifier-wrapper=""><div class="at-theme-light"><div class="at-base notranslate" translate="no"><div class="EuwGd" style="top: 0px; left: 0px;"></div></div></div></div>

</body>
</html>

users/templates/users/login.html
{% extends "users/base.html" %}

{% block content %}

<div>
    <h2>Вхід</h2>
</div>


<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div>
        <label> Ім'я користувача:
            {{ form.username }}
        </label>
    </div>

    <div>
        <label>Пароль:
            {{ form.password }}
        </label>
    </div>

    <div class="grid">
        <button type="submit">Увійти</button>
        <button type="reset" class="secondary">Зкинути</button>
    </div>
    <div class="small text-center">
        <a href="{% url 'users:password_reset' %}" class="text-center"><i>Забули пароль?</i></a>
    </div>
</form>

{% endblock %}

users/templates/users/password_reset.html
{% extends "users/base.html" %}

{% block content %}

    <h2>Зміна пароля</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Запросити зброс пароля</button>
    </form>

{% endblock %}

users/templates/users/password_reset_complete.html
{% extends "users/base.html" %}

{% block content %}

    <h2>Зміна паролю успішна!</h2>

{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends "users/base.html" %}

{% block content %}

    <h2>Введіть новий пароль</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Зберегти новий пароль</button>
    </form>

{% endblock %}

users/templates/users/password_reset_done.html
{% extends "users/base.html" %}

{% block content %}

    <h2>Запрос на зміну паролю надіслано</h2>
    <p>Дотримуйтесь інструкціі яку ми надіслали Вам на поштову скриньку.</p>

{% endblock %}

users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Вітаємо {{ user.username }},</p>
<p>Ви запросили зміну паролю. Будь ласка перейдіть по посиланню:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>Якщо Ви не запрошували зміну паролю, ігноруйте цей лист.</p>
<p>Дякуємо,</p>
<p>Команда STARLINGUA</p>
{% endautoescape %}

users/templates/users/signup.html
{% extends "users/base.html" %}

{% block content %}

<div>
    <h2>Реєстрація</h2>
</div>

<form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    <div>
        <label> Ім'я користувача:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <br>
    <div>
        <label> Поштова адреса (Email):
            {{ form.email }}
        </label>
        <span>{{ form.errors.email }}</span>
    </div>
    <br>    
    <div>
        <label> Пароль:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div>
        <label> Повторіть пароль:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div>
        <label> Роль:
            {{ form.role }}
        </label>
        <span>{{ form.errors.role }}</span>
    </div>
    <div class="grid">
        <button type="submit">Підтвердити</button>
        <button type="reset" class="secondary">Зкинути</button>
    </div>
</form>

{% endblock %}